### PR TITLE
Make `sim` operations exception safe by using `withMockFS`

### LINKED ISSUE #1294: Flaky Byron ThreadNet failure: ImmutableDB is leaking file handles
On current `main` (44d8867c33102766a6b30e6f6a75e3b0b136d5e7):
```console
 $ cabal run byron-test -- --quickcheck-replay="(SMGen 3815441042141447428 1971304436672976329,3)" -p '/simple convergence/'
      Node CoreId (CoreNodeId 0)'s ImmutableDB is leaking file handles
      1 /= 0
```
This bug seems to have been introduced/revealed by #1228; the command above doesn't failure before it (i.e. it fails on af19eff21ff3f7bb190ddf6ccabd2149e51e39d6, but not on d6e35dc919e4af24a07bc4725e5240650ad64abc).

Maybe #1228 is only related insofar as it lead to the exploration of a different STM schedule exhibiting a bug that was already present, just not found before. Also see https://github.com/IntersectMBO/ouroboros-consensus/issues/1105#issuecomment-2122386012.

### PR DESCRIPTION
**Pull request by jasagredo**
See https://github.com/IntersectMBO/ouroboros-consensus/issues/1294#issuecomment-4223745189 for a test-case that uncovered this issue.

### CODE REVIEW

File: fs-sim/src/System/FS/Sim/STM.hs [hunk 1]
```diff
@@ -37,15 +37,35 @@ runSimFS fs act = do
...
+  StrictTMVar m MockFS ->
+  (MockFS -> m (MockFS, Either FsError a)) ->
+  m a
+withMockFS var f = do
+  result <- uninterruptibleMask $ \restore -> do
+    st <- atomically $ takeTMVar var
+    (st', ea) <- restore (f st) `onException` atomically (putTMVar var st)
+    atomically $ putTMVar var st'
+    pure ea
+  either throwIO pure result
```
Comment (jorisdral) [inline fs-sim/src/System/FS/Sim/STM.hs:61]: I'm not sure I understand why it has to be uninterruptible. Maybe we could add an example to the haddocks?

Comment (jorisdral) [reply fs-sim/src/System/FS/Sim/STM.hs:61]: Okay so it is explained here: https://github.com/IntersectMBO/ouroboros-consensus/issues/1294#issuecomment-4223745189

I think what confused me about the haddocks here is that the "masked cleanup" that it talks about is not the code on line 61, but instead I think it means "a masked action that calls `withMockFS`". Maybe haddocks like this would be sufficient?

```suggestion
-- | Bracket-style helper that holds the MockFS lock for the duration of @f@.
--
-- 'withMockFS' is not interruptible while waiting for the `MockFS` TMVar, but the body @f@
-- runs with the caller's original masking state restored.
withMockFS ::
  (MonadSTM m, MonadMask m) =>
  StrictTMVar m MockFS ->
  (MockFS -> m (MockFS, Either FsError a)) ->
  m a
withMockFS var f = do
  result <- uninterruptibleMask $ \restore -> do
    st <- atomically $ takeTMVar var
    (st', ea) <- restore (f st) `onException` atomically (putTMVar var st)
    atomically $ putTMVar var st'
    pure ea
  either throwIO pure result
```

Comment (jasagredo) [reply fs-sim/src/System/FS/Sim/STM.hs:61]: I used a slightly different version of your haddock, but yeah.

**Comment by geo2a** [comment]
I have used Claude Code to vibe draw diagrams in the style of "Designing Data-Intensive Applications" by Martin Kleppmann. I hope I haven't committed a copyright violation by doing this! I found these diagrams quite useful to understand better what happens in https://github.com/IntersectMBO/ouroboros-consensus/issues/1294#issuecomment-4223745189:

file-handle-leak-diagram

**Review by jorisdral — APPROVED** [review]
I had not considered interruptibility when changing this code to use `TMVar`, so this is a good improvement :smile: 

`uninterruptibleMask` is a bit risky because the user of `withMockFS` can put/take from the `TMVar` at will, causing `withMockFS` to block without being interruptible. But since this code is intended for simulation and testing, maybe that is fine? What do you think @jasagredo @geo2a ?

**Comment by jasagredo** [comment]
Discussed it with Joris and concluded that we can merge this as it is only intended for testing.

**Review by geo2a — APPROVED** [review]
